/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package tarea7;

/**
 *
 * @author jocsa
 */
public class CalculadoraJForm extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraJForm
     */
    public CalculadoraJForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Numero8 = new javax.swing.JButton();
        Divison = new javax.swing.JButton();
        Numero7 = new javax.swing.JButton();
        Numero5 = new javax.swing.JButton();
        Numero4 = new javax.swing.JButton();
        Numero6 = new javax.swing.JButton();
        Numero1 = new javax.swing.JButton();
        Numero2 = new javax.swing.JButton();
        Numero3 = new javax.swing.JButton();
        Numero0 = new javax.swing.JButton();
        borrar = new javax.swing.JButton();
        punto = new javax.swing.JButton();
        Numero9 = new javax.swing.JButton();
        Multiplicacion = new javax.swing.JButton();
        Resta = new javax.swing.JButton();
        Suma = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        Igual = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Numero8.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Numero8.setText("8");
        Numero8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero8ActionPerformed(evt);
            }
        });

        Divison.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Divison.setText("÷");
        Divison.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DivisonActionPerformed(evt);
            }
        });

        Numero7.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Numero7.setText("7");
        Numero7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero7ActionPerformed(evt);
            }
        });

        Numero5.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Numero5.setText("5");
        Numero5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero5ActionPerformed(evt);
            }
        });

        Numero4.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Numero4.setText("4");
        Numero4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero4ActionPerformed(evt);
            }
        });

        Numero6.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Numero6.setText("6");
        Numero6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero6ActionPerformed(evt);
            }
        });

        Numero1.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Numero1.setText("1");
        Numero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero1ActionPerformed(evt);
            }
        });

        Numero2.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Numero2.setText("2");
        Numero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero2ActionPerformed(evt);
            }
        });

        Numero3.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Numero3.setText("3");
        Numero3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero3ActionPerformed(evt);
            }
        });

        Numero0.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Numero0.setText("0");
        Numero0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero0ActionPerformed(evt);
            }
        });

        borrar.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        borrar.setText("DEL");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });

        punto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        punto.setText(".");
        punto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoActionPerformed(evt);
            }
        });

        Numero9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Numero9.setText("9");
        Numero9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Numero9ActionPerformed(evt);
            }
        });

        Multiplicacion.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Multiplicacion.setText("x");
        Multiplicacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MultiplicacionActionPerformed(evt);
            }
        });

        Resta.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Resta.setText("-");
        Resta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RestaActionPerformed(evt);
            }
        });

        Suma.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        Suma.setText("+");
        Suma.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SumaActionPerformed(evt);
            }
        });

        jTextField1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Igual.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Igual.setText("=");
        Igual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IgualActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Numero4, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Numero7, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Numero1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Numero0, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(Suma, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(Numero8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(Numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(Divison, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Multiplicacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(Numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGap(18, 18, 18)
                                            .addComponent(Numero3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                    .addGap(18, 18, 18)
                                    .addComponent(Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(18, 18, 18)
                        .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Numero7, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Numero8, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Numero9, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Divison, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero5, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero4, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero6, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Multiplicacion, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Numero1, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Numero3, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Resta, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Suma, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(Numero0, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(punto, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(borrar, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Igual, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Numero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero2ActionPerformed
        if(banderaoperacion){
            this.jTextField1.setText("");
            banderaoperacion=false;
        } 
        if(this.jTextField1.getText().equals("0")){
            this.jTextField1.setText("2");
        }else{
            this.jTextField1.setText(this.jTextField1.getText()+"2");
        }
    }//GEN-LAST:event_Numero2ActionPerformed

    private void DivisonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DivisonActionPerformed
         this.metodo="division";
        this.numero1=Float.parseFloat(this.jTextField1.getText());
        banderaoperacion=true;
        banderapunto=false;
    }//GEN-LAST:event_DivisonActionPerformed

    private void Numero7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero7ActionPerformed
        if(banderaoperacion){
            this.jTextField1.setText("");
            banderaoperacion=false;
        }  
        if(this.jTextField1.getText().equals("0")){
            this.jTextField1.setText("7");
        }else{
            this.jTextField1.setText(this.jTextField1.getText()+"7");
        }
    }//GEN-LAST:event_Numero7ActionPerformed

    private void Numero6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero6ActionPerformed
        if(banderaoperacion){
            this.jTextField1.setText("");
            banderaoperacion=false;
        }  
        if(this.jTextField1.getText().equals("0")){
            this.jTextField1.setText("6");
        }else{
            this.jTextField1.setText(this.jTextField1.getText()+"6");
        }
    }//GEN-LAST:event_Numero6ActionPerformed

    private void Numero0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero0ActionPerformed
       if(banderaoperacion){
            this.jTextField1.setText("");
            banderaoperacion=false;
        } 
        if(this.jTextField1.getText().equals("0")){
            this.jTextField1.setText("0");
        }else{
            this.jTextField1.setText(this.jTextField1.getText()+"0");
        }
    }//GEN-LAST:event_Numero0ActionPerformed

    private void Numero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero1ActionPerformed
        if(banderaoperacion){
            this.jTextField1.setText("");
            banderaoperacion=false;
        }  
        if(this.jTextField1.getText().equals("0")){
            this.jTextField1.setText("1");
        }else{
            this.jTextField1.setText(this.jTextField1.getText()+"1");
        }
    }//GEN-LAST:event_Numero1ActionPerformed

    private void Numero3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero3ActionPerformed
        if(banderaoperacion){
            this.jTextField1.setText("");
            banderaoperacion=false;
        }  
        if(this.jTextField1.getText().equals("0")){
            this.jTextField1.setText("3");
        }else{
            this.jTextField1.setText(this.jTextField1.getText()+"3");
        }
    }//GEN-LAST:event_Numero3ActionPerformed

    private void Numero4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero4ActionPerformed
        if(banderaoperacion){
            this.jTextField1.setText("");
            banderaoperacion=false;
        } 
        if(this.jTextField1.getText().equals("0")){
            this.jTextField1.setText("4");
        }else{
            this.jTextField1.setText(this.jTextField1.getText()+"4");
        }
    }//GEN-LAST:event_Numero4ActionPerformed

    private void Numero5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero5ActionPerformed
        if(banderaoperacion){
            this.jTextField1.setText("");
            banderaoperacion=false;
        } 
        if(this.jTextField1.getText().equals("0")){
            this.jTextField1.setText("5");
        }else{
            this.jTextField1.setText(this.jTextField1.getText()+"5");
        }
    }//GEN-LAST:event_Numero5ActionPerformed

    private void Numero8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero8ActionPerformed
        if(banderaoperacion){
            this.jTextField1.setText("");
            banderaoperacion=false;
        } 
        if(this.jTextField1.getText().equals("0")){
            this.jTextField1.setText("8");
        }else{
            this.jTextField1.setText(this.jTextField1.getText()+"8");
        }
    }//GEN-LAST:event_Numero8ActionPerformed

    private void Numero9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Numero9ActionPerformed
        if(banderaoperacion){
            this.jTextField1.setText("");
            banderaoperacion=false;
        } 
        if(this.jTextField1.getText().equals("0")){
            this.jTextField1.setText("9");
        }else{
            this.jTextField1.setText(this.jTextField1.getText()+"9");
        }
    }//GEN-LAST:event_Numero9ActionPerformed

    private void puntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoActionPerformed
        if(banderaoperacion){
            this.jTextField1.setText("");
            banderaoperacion=false;
        } 
        if(this.jTextField1.getText().equals("")){
            this.jTextField1.setText("0.");
            this.banderapunto=true;
        }else{
             if(!banderapunto){
            this.jTextField1.setText(this.jTextField1.getText()+".");
            this.banderapunto=true;}            
        }
    }//GEN-LAST:event_puntoActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        this.jTextField1.setText("");
        this.banderapunto=false;
        this.metodo="";
        banderaoperacion=false;
    }//GEN-LAST:event_borrarActionPerformed

    private void IgualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IgualActionPerformed
        this.numero2= Float.parseFloat(this.jTextField1.getText());
        if(this.metodo.equals("suma")){
            this.resultado= numero1+numero2;
            if(resultado%1==0){
            this.jTextField1.setText(String.valueOf(Math.round(resultado)));
            }else{
            this.jTextField1.setText(String.valueOf(resultado));}}
        if(this.metodo.equals("resta")){
             this.resultado= numero1-numero2;
            if(resultado%1==0){
            this.jTextField1.setText(String.valueOf(Math.round(resultado)));
            }else{
            this.jTextField1.setText(String.valueOf(resultado));}    
        }
        
        if(this.metodo.equals("multiplicacion")){
             this.resultado= numero1*numero2;
            if(resultado%1==0){
            this.jTextField1.setText(String.valueOf(Math.round(resultado)));
            }else{
            this.jTextField1.setText(String.valueOf(resultado));}    
        }
        
        if(this.metodo.equals("division")){
            if(numero2==0){
                this.jTextField1.setText("NAN");
            }else{
            this.resultado= numero1/numero2;
            if(resultado%1==0){
            this.jTextField1.setText(String.valueOf(Math.round(resultado)));
            }else{
            this.jTextField1.setText(String.valueOf(resultado));}}    
        }
        this.banderaoperacion=true;
        this.banderapunto=false;
        this.metodo="";
    }//GEN-LAST:event_IgualActionPerformed

    private void SumaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SumaActionPerformed
        this.metodo="suma";
        this.numero1=Float.parseFloat(this.jTextField1.getText());
        banderaoperacion=true;
        banderapunto=false;
    }//GEN-LAST:event_SumaActionPerformed

    private void RestaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RestaActionPerformed
        this.metodo="resta";
        this.numero1=Float.parseFloat(this.jTextField1.getText());
        banderaoperacion=true;
        banderapunto=false;
    }//GEN-LAST:event_RestaActionPerformed

    private void MultiplicacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MultiplicacionActionPerformed
         this.metodo="multiplicacion";
        this.numero1=Float.parseFloat(this.jTextField1.getText());
        banderaoperacion=true;
        banderapunto=false;
    }//GEN-LAST:event_MultiplicacionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraJForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraJForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Divison;
    private javax.swing.JButton Igual;
    private javax.swing.JButton Multiplicacion;
    private javax.swing.JButton Numero0;
    private javax.swing.JButton Numero1;
    private javax.swing.JButton Numero2;
    private javax.swing.JButton Numero3;
    private javax.swing.JButton Numero4;
    private javax.swing.JButton Numero5;
    private javax.swing.JButton Numero6;
    private javax.swing.JButton Numero7;
    private javax.swing.JButton Numero8;
    private javax.swing.JButton Numero9;
    private javax.swing.JButton Resta;
    private javax.swing.JButton Suma;
    private javax.swing.JButton borrar;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton punto;
    // End of variables declaration//GEN-END:variables
    private float numero1;
    private float numero2;
    private float resultado;
    private boolean banderapunto=false;   
    private String metodo="";
    private boolean banderaoperacion=false;
}
